### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by directions4** [nickjohnson-dev/treecko#1]
it has a build problem. maybe that rimraf is not included in package.json.

**Comment by nickjohnson-dev** [comment]
Thanks for catching that! I have added rimraf to devDependencies now.

When you get a chance to look at this again, let me know if that resolves the issue you're seeing.

**Comment by directions4** [comment]
clean task is OK! but version number in package.json had not changed

**Comment by nickjohnson-dev** [comment]
I think that the version number should be up to date now. I had an unsynced commit on my machine.
