### ISSUE TITLE
npm only contains dist/index.js

### ISSUE THREAD

**Issue by Kilian** [nickjohnson-dev/treecko#2]
The npm package 3.0.3 is completely unusable because it only contains dist/index.js and thus tries to require a ton of file that aren't there :(

**Comment by Kilian** [comment]
fyi, I published to my own scoped package and that works, so a proper update and re-publish should be fine! :+1:

**Comment by nickjohnson-dev** [comment]
Hi, thanks for reporting this!

I actually published a fix for this a few days ago after someone at my job noticed it, but I'm realizing now that it got caught in the private npm registry and never got out to npmjs.org. 😅 

I'm glad you found a workaround. Sorry for your trouble.

3.0.4 is available now, and it should have all the correct files.

Let me know if you encounter any more issues.
